# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creatorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TextQuestionName = QtWidgets.QLabel(self.centralwidget)
        self.TextQuestionName.setObjectName("TextQuestionName")
        self.horizontalLayout_3.addWidget(self.TextQuestionName)
        self.NameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.NameBox.setObjectName("NameBox")
        self.horizontalLayout_3.addWidget(self.NameBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.ContentSpace = QtWidgets.QTabWidget(self.centralwidget)
        self.ContentSpace.setObjectName("ContentSpace")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.QuestionText = QtWidgets.QTextEdit(self.tab)
        self.QuestionText.setObjectName("QuestionText")
        self.verticalLayout_4.addWidget(self.QuestionText)
        self.ContentSpace.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddButton = QtWidgets.QToolButton(self.tab_2)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout.addWidget(self.AddButton)
        self.DeleteButton = QtWidgets.QToolButton(self.tab_2)
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout.addWidget(self.DeleteButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.ExpectedOutputTable = QtWidgets.QTableWidget(self.tab_2)
        self.ExpectedOutputTable.setObjectName("ExpectedOutputTable")
        self.ExpectedOutputTable.setColumnCount(0)
        self.ExpectedOutputTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.ExpectedOutputTable)
        self.ContentSpace.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.ContentSpace)
        self.FinalConfirmBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.FinalConfirmBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.FinalConfirmBox.setObjectName("FinalConfirmBox")
        self.verticalLayout.addWidget(self.FinalConfirmBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionNew)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.ContentSpace.setCurrentIndex(1)
        self.FinalConfirmBox.accepted.connect(MainWindow.DoOutput)
        self.AddButton.clicked.connect(MainWindow.AddButtonClicked)
        self.DeleteButton.clicked.connect(MainWindow.DeleteButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextQuestionName.setText(_translate("MainWindow", "Question Name"))
        self.ContentSpace.setTabText(self.ContentSpace.indexOf(self.tab), _translate("MainWindow", "Question Text"))
        self.AddButton.setText(_translate("MainWindow", "Add..."))
        self.DeleteButton.setText(_translate("MainWindow", "Delete Selected"))
        self.ContentSpace.setTabText(self.ContentSpace.indexOf(self.tab_2), _translate("MainWindow", "Expected Outputs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionNew.setText(_translate("MainWindow", "New"))
